name: Deploy to Azure Container Apps

# Run when commits are pushed to feat/migrate-swa-to-aca
on:
  workflow_dispatch:
  push:
    # Run when commits are pushed to mainline branch (main or master)
    # Set this to the mainline branch you are using
    branches:
      - feat/migrate-swa-to-aca

# Set up permissions for deploying with secretless Azure federated credentials
# https://learn.microsoft.com/en-us/azure/developer/github/connect-from-azure?tabs=azure-portal%2Clinux#set-up-azure-login-with-openid-connect-authentication
permissions:
  id-token: write
  contents: read


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AZURE_ENV_NAME: microblog-ai-aca-02
      AZURE_LOCATION: eastus2
      # Azure OpenAI Configuration
      AZURE_OPENAI_API_VERSION: "2024-05-01-preview"
      AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install azd
        uses: Azure/setup-azd@v2

      - name: Log in with Azure (OIDC)
        uses: azure/login@v1
        env:
          AZURE_CREDS: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":" ","tenantId":"${{ secrets.AZURE_TENANT_ID }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}'
        with:
          creds: ${{ env.AZURE_CREDS }}

      - name: Debug Auth Identity
        run: |
          echo "Using identity: $(az account show --query user.name -o tsv)"
          echo "Subscription: $(az account show --query name -o tsv)"

      - name: Azure CLI Command
        run: |
          az account show
          az account set --subscription ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: microblog-ai-aca-02
          AZURE_LOCATION: eastus2
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_VERSION: "2024-05-01-preview"
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}

      - name: Build Application
        run: npm run build

      - name: Provision Infrastructure
        run: azd provision --no-prompt
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_ENV_NAME: microblog-ai-aca-02
          AZURE_LOCATION: eastus2
          AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
          AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}
          AZURE_OPENAI_API_VERSION: "2024-05-01-preview"
          AZURE_OPENAI_DEPLOYMENT_NAME: ${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}          