name: Security Checks

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  security:
    name: Run Security Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Scorecard Security Check
        uses: ossf/scorecard-action@v2
        with:
          repo: ${{ github.repository }}
          results_file: results.sarif
